# Generated by Django 4.2.1 on 2023-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_store', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('price', models.IntegerField()),
                ('network', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
